name: Ultralesson Mobile Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

  mobile_test:
    runs-on: macos-latest
    needs: build
    strategy:
      matrix:
        api-level: [ 28 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: download appium
        run: |
          npm install -g appium@next
          appium driver install uiautomator2
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          force-avd-creation: true
          disable-animations: true
          script: ./gradlew runMobileTests --stacktrace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mobile_test
          path: build/mobile-reports
