# This workflow uses actions that are not certified by GitHub.
    # They are provided by a third-party and are governed by
    # separate terms of service, privacy policy, and support
    # documentation.
    # This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
    # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
    
    name: Ultralesson Mobile Automation
    
    on:
     push:
       branches: [ main, workflow_dispatch ]
     pull_request:
       branches: [ main, workflow_dispatch ]
    
    jobs:
     build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
     uses: actions/setup-java@v2
     with:
     java-version: '11'
     distribution: 'temurin'
     - name: Build with Gradle
     uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
     with:
     arguments: build
     mobile_test:
     runs-on: macos-latest
     needs: build
     strategy:
     matrix:
     api-level: [ 28 ]
     steps:
     - name: checkout
     uses: actions/checkout@v2
    
     - name: Gradle cache
     uses: gradle/gradle-build-action@v2
    
     - name: AVD cache
     uses: actions/cache@v2
     id: avd-cache
     with:
     path: |
     ~/.android/avd/*
     ~/.android/adb*
     key: avd-${{ matrix.api-level }}
    
     - name: download appium
     run: |
     npm install -g appium@next
     appium driver install uiautomator2
     - name: run tests
     uses: reactivecircus/android-emulator-runner@v2
     with:
     api-level: ${{ matrix.api-level }}
     target: google_apis
     force-avd-creation: true
     disable-animations: true
     script: ./gradlew runMobileTests --stacktrace
    
     - name: Upload Artifacts
     uses: actions/upload-artifact@v2
     if: ${{ always() }}
     with:
     name: mobile_test
     path: build/mobile-reports
